.github/workflows/deploy_git_tag.yml, .github/workflows/deploy_pubspec.yml, .github/workflows/promote.yml
Changes the Slack channel for deployment messages to the new mobile-deployments channel
See https://github.com/customerio/issues/issues/9014
=> ci: changes Slack deployment message channel

.github/workflows/deploy_git_tag.yml
semantic-release has fixed the conventional-commits issue in v22. Therefore, we can remove the workaround from our CI configurations and use the latest version of semantic-release for deployments. 
This PR updates the CI config to have the latest version of semantic-release.
=> ci: remove workaround for semantic-release issue skipping deployment

android/build.gradle
version bump for: stack-overflow caused by BQ recursion (https://github.com/customerio/customerio-android/pull/251) ([365a5b6](https://github.com/customerio/customerio-android/commit/365a5b690ed37667dfb6782629ad56743d97904d))
=> fix: stack-overflow caused by BQ recursion

.github/workflows/deploy_git_tag.yml
Similar to other PRs in other repos, I suggest we use latest version of tool instead of a hard-coded version.
=> ci: use latest version of deploy tool

.github/workflows/deploy_git_tag.yml
The iOS SDK experienced a deployment failure on `main` because of a GH Action that we depend on. 
I installed a workaround in the iOS SDK until the GH action gets fixed. This PR applies the same workaround here.
=> ci: fix installing sd tool needed for deployment

android/build.gradle, apps/amiapp_flutter/android/app/build.gradle, apps/amiapp_flutter/android/build.gradle, apps/amiapp_flutter/android/settings.gradle, apps/amiapp_flutter/lib/src/app.dart, apps/amiapp_flutter/lib/src/screens/dashboard.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, pubspec.yaml
helps: [MBL-229 : Proguard rules for Android](https://linear.app/customerio/issue/MBL-229/proguard-rules-for-android)
What it does:
- Bumps the android SDK version
- Applied changes from[ Deprecated imperative apply of Flutter's Gradle plugins](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)
=> fix: added proguard rules for R8 strict mode

README.md
The current get started guide with the link on pub.dev doesn't link to the correct hompeage it goes to a page that is not found.
=> chore: update docs link text in README

apps/amiapp_flutter/ios/Flutter/AppFrameworkInfo.plist, apps/amiapp_flutter/ios/Podfile, apps/amiapp_flutter/ios/Runner.xcodeproj/project.pbxproj, apps/amiapp_flutter/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, apps/amiapp_flutter/ios/Runner/AppDelegate.swift, apps/amiapp_flutter/lib/main.dart, apps/amiapp_flutter/lib/src/screens/dashboard.dart, apps/amiapp_flutter/pubspec.yaml
Part of: https://linear.app/customerio/issue/MBL-383/[bug]-customer-unable-to-handle-push-notification-event-on-ios-with
Tests [this iOS bug fix](https://github.com/customerio/customerio-ios/pull/743) in FCM sample app, while also testing local push notifications in the app. 
This PR: 
- displays local push notifications, which we use for QA testing local push
- adds a push event handler for local push in `AppDelegate`. 
After this PR, the FCM sample app will have 3 push event handlers: CIO SDK, flutterfire, and the host iOS app (AppDelegate). This environment allows us to test the iOS bug that is caused when there are at least 2 push event handlers installed in an app. 
Testing:
* Local push QA regression tests. 
* Non-CIO FCM push QA regression tests (send a FCM push from Firebase …
=> chore: test multiple push event handlers in sample app

ios/Classes/SwiftCustomerIoPlugin.swift
Ticket: https://linear.app/customerio/issue/MBL-358/
When the native iOS in-app module communicates with the Flutter SDK, it currently does so on the native background thread. According to [flutter docs](https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading), it should be the main thread. 
* In Flutter sample app, do things that would make the in-app global event listener to trigger. Before this bug fix, you should see error show up in Xcode console. After the bug fix, you should no longer see the error. 
* I searched the Flutter source code where everywhere that `invokeMethodInBackground` is called to see if there were any other places where we could be having native code communicate to Flutter SDK and I only found the 1 place that I modified.
=> fix: send native to flutter messages on main thread

android/src/main/kotlin/io/customer/customer_io/CustomerIOExtensions.kt
fixes: #141 
part of [MBL-494](https://linear.app/customerio/issue/MBL-494/button-with-dismiss-behavior-do-not-close-in-app-message-on-some)
- Return `boolean` value for unit calls as native calls must return some value
=> chore: wrap unit calls with boolean result

android/build.gradle, android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/messagingpush/CustomerIOPushMessaging.kt, apps/amiapp_flutter/android/app/build.gradle
part of [MBL-621](https://linear.app/customerio/issue/MBL-621/update-native-sdk-dependencies-to-data-pipelines-release)
- Updated Android native SDK dependencies from Tracking to Data Pipelines
- Removed outdated imports and commented out legacy SDK calls to facilitate incremental updates with new implementation
- Added TODOs to each commented legacy SDK call to ensure nothing is overlooked
=> chore: update Android native dependencies to Data Pipelines

apps/amiapp_flutter/ios/Podfile, ios/customer_io.podspec, ios/customer_io_richpush.podspec, pubspec.yaml
closes [MBL-622](https://linear.app/customerio/issue/MBL-622/fix-ios-native-sdk-version-in-flutter-sdk)
- Added `native_sdk_version` in `pubspec.yaml` to specify iOS SDK version
- Updated `customer_io.podspec` to reference `native_sdk_version` from `pubspec.yaml`
- Modified `customer_io.podspec` to include FCM as a subspec for customer Podfile reference
- Created `customer_io_richpush.podspec` using `native_sdk_version`, with FCM as subspec for NSE reference in customer Podfile
- Updated sample app's Podfile
```
target 'Runner' do
pod 'CustomerIO/MessagingPushFCM', '~> 3.5.1'
end
target 'NotificationServiceExtension' do
pod 'CustomerIO/MessagingPushFCM', '~> 3.5.1'
end
```
```
target 'Runner' do
pod 'customer_io/fcm', :path => '.symlinks/plugins/customer_io/ios'
end
target …
```
=> chore: fix ios native sdk version

.github/workflows/build-sample-apps.yml, apps/amiapp_flutter/.env.example, apps/amiapp_flutter/lib/src/customer_io.dart, apps/amiapp_flutter/lib/src/data/config.dart, apps/amiapp_flutter/lib/src/screens/settings.dart
closes: [MBL-624: Flutter as source as Fly](https://linear.app/customerio/issue/MBL-624/flutter-as-source-as-fly)
changes:
- update workflow to cater cdp API key
- updated the SDKConfig of the sample app to be able to test it
=> chore: hook sample app with flutter source

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/constant/Keys.kt
part of [MBL-620](https://linear.app/customerio/issue/MBL-620/initialization)
- Initialized native Android SDK using configuration provided by Flutter
- Removed unused constants related to initialization
=> chore: initialize native android sdk in flutter

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/constant/Keys.kt, apps/amiapp_flutter/lib/src/app.dart, ios/Classes/Keys.swift, ios/Classes/SwiftCustomerIoPlugin.swift, lib/customer_io.dart, lib/customer_io_const.dart, lib/customer_io_method_channel.dart, lib/customer_io_platform_interface.dart, test/customer_io_method_channel_test.dart, test/customer_io_test.dart, test/customer_io_test.mocks.dart
closes: https://linear.app/customerio/issue/MBL-631/identify-and-attributes
changes:
- Method signature 
- Ability to add attributes for identified and anonymous profile 
- Tests updates
=> chore: added identify and attributes

apps/amiapp_flutter/lib/src/app.dart, apps/amiapp_flutter/lib/src/customer_io.dart, apps/amiapp_flutter/lib/src/data/config.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, apps/amiapp_flutter/lib/src/utils/extensions.dart, apps/amiapp_flutter/lib/src/widgets/settings_form_field.dart
part of [MBL-623](https://linear.app/customerio/issue/MBL-623/update-sample-app-settings-screen)
- Adjusted settings UI in sample app to align with Data Pipelines configuration
- Modified SDK initialization to use stored values
- Updated input requirements to make non-required fields optional
=> chore: update sample app settings ui for data pipelines

apps/fastlane/helpers/build_helper.rb
This PR adds the Firebase Distribution groups for 'feature-branch', 'next', and 'public' in addition to the current 'all-builds' and 'stable-builds' groups.
=> chore: update Fastfile to publish to new distribution groups

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/constant/Keys.kt, apps/amiapp_flutter/lib/main.dart, apps/amiapp_flutter/lib/src/screens/dashboard.dart, apps/amiapp_flutter/lib/src/screens/events.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, ios/Classes/Keys.swift, ios/Classes/SwiftCustomerIoPlugin.swift, lib/customer_io.dart, lib/customer_io_const.dart, lib/customer_io_method_channel.dart, lib/customer_io_platform_interface.dart, test/customer_io_method_channel_test.dart, test/customer_io_test.dart, test/customer_io_test.mocks.dart
closes: [MBL-633](https://linear.app/customerio/issue/MBL-633/track-events)
- Revised SDK `track` method to use new parameter names
- Updated native code files, tests, and sample app to reflect these changes
```dart
CustomerIO.track(name: "Favourites Viewed");
CustomerIO.track(name: "Movie Watched", attributes: {
"movie_name": "The Incredibles",
"watch_time_in_minutes": 102,
});
```
```
CustomerIO.instance.track(name: "Favourites Viewed");
CustomerIO.instance.track(name: "Movie Watched", properties: {
"movie_name": "The Incredibles",
"watch_time_in_minutes": 102,
});
```
=> chore: update event tracking parameters

.github/workflows/build-sample-apps.yml, apps/fastlane/helpers/version_helper.rb
- Modified build sample apps task to fail if either Android or iOS build fails
- Updated `version_helper.rb` to align with React Native and prevent failure when time starts with `0`
- Created PR as I observed an issue in Data Pipelines support changes where tasks didn't fail on individual build failures, leading to false positives.
- Once merged to `main`, I'll merge this change to the Data Pipelines feature branch.
=> ci: ensure task fails if any build fails

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/constant/Keys.kt, apps/amiapp_flutter/lib/src/app.dart, apps/amiapp_flutter/lib/src/data/config.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, apps/amiapp_flutter/lib/src/utils/extensions.dart, ios/Classes/Keys.swift, ios/Classes/SwiftCustomerIoPlugin.swift, lib/customer_io.dart, lib/customer_io_const.dart, lib/customer_io_method_channel.dart, lib/customer_io_platform_interface.dart, lib/extensions/map_extensions.dart, test/customer_io_method_channel_test.dart, test/customer_io_test.dart, test/customer_io_test.mocks.dart
closes: [MBL-634](https://linear.app/customerio/issue/MBL-634/screen-events)
- Updated SDK `screen` method to use revised parameter names
- Adjusted native SDK, tests, and sample app accordingly
```dart
CustomerIO.screen(name: "Favourites");
CustomerIO.screen(name: "Settings", attributes: {
"source": "Dashboard",
"is_logged_in": true,
});
```
```dart
CustomerIO.instance.screen(title: "Favourites");
CustomerIO.instance.screen(title: "Settings", properties: {
"source": "Dashboard",
"is_logged_in": true,
});
```
=> chore: update screen tracking parameters

android/src/main/AndroidManifest.xml, android/src/main/res/values/customer_io_config.xml
part of [MBL-635](https://linear.app/customerio/issue/MBL-635/user-agents)
- Added `customer_io_config.xml` to include wrapper SDK source and version information
- Updated `AndroidManifest` to reference `customer_io_config.xml` and update `meta-data`, allowing native Android SDK to use this information for creating the user agent
```
Customer.io Android Client/4.3.0 (Google Pixel 6; 34) io.customer.amiapp_flutter/1.0
```
```
Customer.io Flutter Client/1.5.2 (Google Pixel 6; 34) io.customer.amiapp_flutter/1.0
```
Script and CI updates for version updates will be handled in a separate PR.
=> chore: add android user agent client source

ios/Classes/Bridge/SdkClientConfiguration.swift, ios/Classes/SwiftCustomerIoPlugin.swift
part of [MBL-635](https://linear.app/customerio/issue/MBL-635/user-agents)
- Added `SdkClientConfiguration.swift` to configure and override `SdkClient`
- Overrode `SdkClient` before initializing native iOS SDK, enabling native iOS to use this configuration for creating the user agent
```
Customer.io iOS Client/3.5.1 (arm64; iOS 18.0) io.customer.amiapp.flutter/1.0.0
```
```
Customer.io Flutter Client/1.5.2 (arm64; iOS 18.0) io.customer.amiapp.flutter/1.0.0
```
=> chore: configure ios user agent client source

android/src/main/kotlin/io/customer/customer_io/constant/Keys.kt, android/src/main/kotlin/io/customer/customer_io/messagingpush/CustomerIOPushMessaging.kt, apps/amiapp_flutter/lib/src/customer_io.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, ios/Classes/Keys.swift, ios/Classes/MessagingPush/CustomerIOMessagingPush.swift, ios/Classes/SwiftCustomerIoPlugin.swift, lib/customer_io_const.dart, lib/messaging_push/method_channel.dart, lib/messaging_push/platform_interface.dart
part of: [MBL-661](https://linear.app/customerio/issue/MBL-661/push-module-configuration-update)
- Added method to fetch registered device token aligning with other SDKs
- Introduced `CustomerIOMessagingPush` iOS class to enable iOS Flutter apps to communicate using `customer_io_messaging_push` push channel
- Sample app fixes to fetch and display registered device token
Fetch registered device token:
```swift
CustomerIO.pushMessaging.getRegisteredDeviceToken() // Nullable String
```
=> chore: fetch registered device token

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, ios/Classes/SwiftCustomerIoPlugin.swift, test/customer_io_test.dart
closes: [MBL-638: Register Device](https://linear.app/customerio/issue/MBL-638/register-device)
changes:
- added support for register device token manually 
```
CustomerIO.instance.registerDeviceToken(deviceToken: token);
```
=> chore: register device token

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/constant/Keys.kt, ios/Classes/Keys.swift, ios/Classes/SwiftCustomerIoPlugin.swift, lib/customer_io.dart, lib/customer_io_const.dart, lib/customer_io_method_channel.dart, lib/customer_io_platform_interface.dart, test/customer_io_method_channel_test.dart, test/customer_io_test.dart, test/customer_io_test.mocks.dart
closes: [MBL-637: Device Attributes](https://linear.app/customerio/issue/MBL-637/device-attributes)
=> chore: added device attributes support

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, ios/Classes/SwiftCustomerIoPlugin.swift, lib/customer_io_const.dart, lib/customer_io_enums.dart, lib/customer_io_method_channel.dart, test/customer_io_method_channel_test.dart, test/customer_io_test.dart
closes: [MBL-677: Enable Metric Event Tracking in Flutter SDK](https://linear.app/customerio/issue/MBL-677/enable-metric-event-tracking-in-flutter-sdk)
=> chore: manual metric tracking

android/src/main/kotlin/io/customer/customer_io/CustomerIoPlugin.kt, android/src/main/kotlin/io/customer/customer_io/messagingpush/CustomerIOPushMessaging.kt
part of: [MBL-661](https://linear.app/customerio/issue/MBL-661/push-module-configuration-update)
- Set up push messaging module for Flutter Android apps using customer provided configurations
- Moved native Android push module initialization to `CustomerIOPushMessaging.kt` to handle push related operations into a single module file
=> chore: configure android push module

.github/workflows/build-sample-apps.yml, apps/amiapp_flutter/ios/Env.swift.example, apps/amiapp_flutter/ios/NotificationServiceExtension/NotificationService.swift, apps/amiapp_flutter/ios/Runner/AppDelegate.swift, apps/amiapp_flutter/lib/main.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, lib/customer_io.dart
part of: [MBL-662](https://linear.app/customerio/issue/MBL-662/initialize-push-module-in-flutter-sdk)
- Updated `pushMessaging` to static property, allowing customers to access it without using `instance`
- Initialized `MessagingPush` module in `AppDelegate` and NSE
- Disabled push permission request on iOS app launch to align with Flutter Android and other platforms
- Updated build sample apps workflow to configure `CdpApiKey` in iOS `Env` file and updated example iOS `Env` file
```dart
CustomerIO.instance.pushMessaging.getRegisteredDeviceToken()
```
```dart
CustomerIO.pushMessaging.getRegisteredDeviceToken()
```
=> chore: initialize messaging push module

android/src/main/kotlin/io/customer/customer_io/CustomerIOExtensions.kt, android/src/main/kotlin/io/customer/customer_io/CustomerIOPlugin.kt, android/src/main/kotlin/io/customer/customer_io/bridge/NativeModuleBridge.kt, android/src/main/kotlin/io/customer/customer_io/messaginginapp/CustomerIOInAppMessaging.kt, android/src/main/kotlin/io/customer/customer_io/messagingpush/CustomerIOPushMessaging.kt, android/src/main/kotlin/io/customer/customer_io/messagingpush/PushMessagingExtensions.kt, android/src/main/kotlin/io/customer/customer_io/utils/MapExtensions.kt, android/src/main/kotlin/io/customer/customer_io/utils/StringExtensions.kt, pubspec.yaml
part of: [MBL-657](https://linear.app/customerio/issue/MBL-657/refactor-and-clean-up-android-code-in-flutter-sdk)
- Moved extensions to dedicated files for better organization
- Renamed `getAsTypeOrNull` to `getAs` for simplicity while retaining functionality
- Renamed `CustomerIoPlugin` to `CustomerIOPlugin` to align with naming conventions
- Renamed `CustomerIOPluginModule` to `NativeModuleBridge` for clarity, as it's an internal class and `CustomerIO` prefix looked redundant
=> chore: rename android classes and method extensions

ios/Classes/CustomerIOPlugin.h, ios/Classes/CustomerIOPlugin.m, ios/Classes/CustomerIoPlugin.h, ios/Classes/MessagingInApp/CustomerIOInAppEventListener.swift, ios/Classes/MessagingInApp/CustomerIOInAppMessaging.swift, ios/Classes/SwiftCustomerIOPlugin.swift, pubspec.yaml
part of: [MBL-658](https://linear.app/customerio/issue/MBL-658/refactor-and-clean-up-ios-code-in-flutter-sdk)
- Moved in-app initialization into dedicated module class
- Moved `InAppEventListener` to a separate file for better organization
- Corrected naming typos and updated class/file names in iOS from `CustomerIo` to `CustomerIO` to align with standard naming conventions
=> chore: refactor ios in-app classes and fix naming

android/build.gradle, android/src/main/kotlin/io/customer/customer_io/CustomerIOPlugin.kt, apps/amiapp_flutter/.gitignore, apps/amiapp_flutter/ios/Podfile, apps/amiapp_flutter/lib/src/customer_io.dart, apps/amiapp_flutter/lib/src/data/config.dart, apps/amiapp_flutter/lib/src/screens/settings.dart, apps/amiapp_flutter/lib/src/utils/extensions.dart, apps/amiapp_flutter/lib/src/widgets/settings_form_field.dart, apps/amiapp_flutter/pubspec.lock, ios/Classes/Bridge/CustomerIOSDKConfigMapper.swift, lib/config/customer_io_config.dart, lib/customer_io_enums.dart, pubspec.yaml, test/customer_io_config_test.dart
closes: [MBL-758](https://linear.app/customerio/issue/MBL-758/add-config-to-flutter-sdk)
- Added `screenViewUse` config to disable sending screen view events to server, allowing local usage only
- Updated Android SDK to version `4.5.0` and iOS SDK to version `3.7.1` to support new `ScreenView` configuration option
- Modified native code files to pass `screenViewUse` configuration to native SDKs for appropriate handling
- Updated relevant tests in SDK
- Updated sample app to allow `screenViewUse` configuration to be modified from the settings page for testing purposes
- Added minor updates and fixes to sample app code
- `Analytics` -> Sends all screen events to the server (same as before) - Default behavior
- `InApp` -> Retains screen events locally for in-app use only
```dart …
```
=> feat: add option to disable screen view usage

apps/amiapp_flutter/android/app/src/main/AndroidManifest.xml, apps/amiapp_flutter/ios/Runner/Info.plist, apps/amiapp_flutter/lib/src/screens/login.dart, apps/amiapp_flutter/pubspec.lock
part of: [MBL-742](https://linear.app/customerio/issue/MBL-742/has-easy-to-understand-app-name)
- Renamed app from `Flutter Sample` to `Flutter`
- Updated app name on the Login Screen for consistency
- Lock file updates
Please refer to linked ticket for more details about these changes.
**Launcher**
_iOS_
_Android_
**Login Screen**
=> chore: update sample app name

.github/workflows/build-sample-apps.yml, apps/fastlane/helpers/build_helper.rb
part of: [MBL-710](https://linear.app/customerio/issue/MBL-710/single-app-per-platform-distributed-to-firebase)
- Updated `Build Sample Apps` action to push sample app to relevant channels
- Modified `get_build_test_groups` lane to decouple from GitHub and accept arguments for passing Firebase distribution groups when distributing sample apps
Please refer to linked ticket for detailed expectations regarding channel distribution.
=> chore: update sample app groups

.github/workflows/build-sample-apps.yml
- Fixed `commitsAheadCount` in `BuildInfoMetadata`
- Updated workflow to add fallback for cases where tags are not fetched properly
| Before |  After |
|-|-|
| ![img_before](https://github.com/user-attachments/assets/6a57f1a1-06b9-4c15-9099-be9154c2df09) | ![img_after](https://github.com/user-attachments/assets/e093fa28-1823-467a-9439-4c3e84402b7e) |
=> chore: fix commits ahead count

apps/amiapp_flutter/pubspec.lock, pubspec.yaml
Pulling in the latest [iOS SDK release](https://github.com/customerio/customerio-ios/releases/tag/3.8.0)
This fixes an issue with [displaying in-app messaging](https://github.com/customerio/customerio-ios/pull/858)
=> fix: Incorrectly scrolling content for in-app modal messages positioned top/bottom

apps/amiapp_flutter/lib/src/utils/build_info.dart, apps/fastlane/Fastfile
- Replaced `update_pubspec_version` function call with `update-version` script to ensure a consistent SDK version update across all relevant files
- Previously, `update_pubspec_version` only updated `pubspec.yaml` causing a mismatch in SDK info displayed in sample app's build info
| Before | After
| - | - |
| ![before](https://github.com/user-attachments/assets/3b0e4b2c-2add-44bb-ac1f-16f684965bb3) | ![after](https://github.com/user-attachments/assets/50b16424-8e15-42f5-af02-252bdcc78e7a) |
=> chore: fix sdk version in sample app build info

.github/workflows/tag-and-deploy.yml
`codeclimate/velocity-deploy-action` Github action started [failing](https://github.com/customerio/customerio-expo-plugin/actions/runs/14379532878/job/40319773344), which is blocking SDK release, we are temporarily disabling it to enables releasing
=> chore: Remove Code Climate Velocity Deployment

.github/workflows/build-sample-app-for-sdk-release.yml, .github/workflows/tag-and-deploy.yml
Closes: [MBL-1053](https://linear.app/customerio/issue/MBL-1053/auto-create-testbed-releases-for-every-sdk-release)
This PR triggers a sample apps public release build after the SDK has been deployed successfully so that internal stakeholders always have up to date versions to test with.
I am not entirely sure if the package will be immediately available after publishing before it can be used to build the sample app or we need a delay. Starting out with immediate trigger and we can revise later if the build fails.
=> chore: Trigger sample apps public builds after deployment is successful

ios/Classes/MessagingInApp/CustomerIOInAppMessaging.swift
Closes: [MBL-1052](https://linear.app/customerio/issue/MBL-1052/flutter-sdk-region-is-not-set-correctly-by-default)
In case of a customer omitting the `region` property from their SDK config, initializing in-app module failed.
The flutter bridge to iOS native SDK that is initializing In-App module is using an extension `MessagingInAppConfigBuilder.from([String: Any?])`. It was attempting to create `MessagingInAppConfigOptions` but it silently failed when an error is thrown.
The Flutter bridge shouldn't silently fail and should log an error that initializing in-app module has failed
=> chore: Log error if swift bridge fails to create MessagingInAppConfigBuilder

android/build.gradle, apps/amiapp_flutter/ios/Podfile, apps/amiapp_flutter/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, apps/amiapp_flutter/pubspec.lock, pubspec.yaml
part of [MBL-1052](https://linear.app/customerio/issue/MBL-1052/flutter-sdk-region-is-not-set-correctly-by-default)
- Updated iOS SDK version to [3.8.2](https://github.com/customerio/customerio-ios/releases/tag/3.8.2)
- Updated Android SDK version to [4.5.8](https://github.com/customerio/customerio-android/releases/tag/4.5.8) ([4.5.7](https://github.com/customerio/customerio-android/releases/tag/4.5.7) included)
- Ran the sample app which updated lock files and IDE related files accordingly
=> fix: make region optional in SDK config for iOS

.github/workflows/reusable-build-sample-apps.yml, .github/workflows/test.yml, android/build.gradle, android/src/main/kotlin/io/customer/customer_io/bridge/MethodCallExtensions.kt, android/src/test/kotlin/io/customer/customer_io/bridge/MethodCallExtensionsTest.kt
This PR improves the Android native module by fixing how Kotlin `Result` types are handled in method calls, and adds proper CI support for running Android native tests.
- Fixed handling of Kotlin `Result` types in Flutter method calls
- Added proper unwrapping of `Result` objects before sending responses to Flutter
- Implemented unit tests to verify correct behavior of different return types
- Updated the test workflow to run Android native tests as part of CI
- Set up the Android environment properly for testing
- Added increased heap memory allocation for Gradle to prevent OOM errors
- Added unit tests to the sample app build workflow for more comprehensive testing
- Added unit tests for `MethodCallExtensions` to verify:
- Handling of successful calls returning regular values
- Handling …
=> fix: unit result type handling

android/build.gradle, apps/amiapp_flutter/pubspec.lock
part of: [MBL-940](https://linear.app/customerio/issue/MBL-940/android-crash-on-flutter-211-sdks)
- Updated native Android SDK to version `4.6.1` to fix an issue where Android app could crash when restored from background while a modal in-app message was active and native Android SDK was not initialized
- See https://github.com/customerio/customerio-android/pull/561 for more details
=> fix: finish modal message early if native android sdk not initialized on restore

apps/amiapp_flutter/lib/src/app.dart, apps/amiapp_flutter/lib/src/data/screen.dart, apps/amiapp_flutter/lib/src/screens/dashboard.dart, apps/amiapp_flutter/lib/src/screens/inline_messages.dart
closes: https://linear.app/customerio/issue/MBL-1172/demo-and-test-in-flutter-sample-app
- New Screen: InlineMessagesScreen with 3 inline message placeholders and skeleton content
- Navigation: Added "Test Inline Messages" button to dashboard
- Element IDs: inline-top, inline-middle, inline-bottom for testing different message placements
- Layout: Alternating inline message views and skeleton loading blocks mimicking real content
- Platform Views: Proper sizing constraints (120px height) to prevent layout errors while allowing native content display
- Auto Resizing of the view is still under progress hence you will see default size of placeholders. Once thats done the inline placeholders will be 0 by default
=> chore: sample app with flutter view usage

.github/workflows/auto-update-native-sdks.yml
- Leverage existing sample app build infrastructure instead of custom logic and repeated app creation steps
- Workflow now relies on automatic PR-triggered sample app builds
Changes:
- Simplified sample app testing approach
The workflow will now:
1. Update native SDK versions in plugin
2. Test plugin analysis and unit tests
3. Create PR with detailed release notes
4. Sample apps automatically build via existing PR workflows
=> ci: improve auto-update native SDKs workflow

android/build.gradle, apps/amiapp_flutter/android/app/src/main/AndroidManifest.xml, apps/amiapp_flutter/pubspec.lock
Closes: [MBL-731](https://linear.app/customerio/issue/MBL-731/flutter-enable-setting-android-message-channel-name)
This PR adds the ability for SDK customers to configure the messaging channel where CIO push notifications are shown for on Android Oreo and higher. There are 3 values that can be configured:
- `io.customer.notification_channel_id` - Custom channel identifier
- `io.customer.notification_channel_name` - Custom channel display name
- `io.customer.notification_channel_importance` - Channel importance level
If config are not provided, defaults are used to create a default channel
=> feat: Add ability to configure messaging channels for local notifications

.github/workflows/check-api-changes.yml, customerio-flutter.api, lib/customer_io.dart, pubspec.yaml, scripts/check_api_changes.sh, scripts/extract_api.sh, scripts/filter_api.dart
Closes: [MBL-1294](https://linear.app/customerio/issue/MBL-1294/flutter-automate-public-api-breaking-changes)
This PR introduces automated API change detection to prevent accidental breaking changes to the public API surface.
✅ New CI Workflow
- Replaces manual API extraction with automated change detection
- Fails CI if public API changes are detected without updating baseline
- Uses local dev dependencies for reproducible builds
✅ Enhanced Scripts
- `check_api_changes.sh`: New script that compares current API against baseline
- `extract_api.sh`: Updated with error handling and local dependency usage
- `filter_api.dart`: Added alphabetical sorting for deterministic output across environments
✅ Dependency Management
- Moved dart_apitool from global to dev dependency in pubspec.yaml
- …
=> chore: Prevent accidental public API changes

.github/workflows/auto-update-native-sdks.yml
Problem
The auto-update native SDK workflow runs daily and creates duplicate PRs when one already exists for the same updates, leading to multiple open PRs for identical SDK version updates.
Solution
Added duplicate detection logic that:
- Checks for existing open PRs using gh pr list --state=open --json number,title
- Uses exact title matching with jq select(.title == $title) to avoid false positives
- Generates expected title using the same logic as PR creation step
- Skips PR creation conditionally when duplicates are found
- Provides clear logging when PRs are skipped due to duplicates
Key Features
- ✅ Exact matching only - prevents substring/version number false matches
- ✅ Safe parameter handling - uses jq --arg to avoid shell injection
- ✅ Conditional execution - only creates PRs …
=> ci: remove update duplications 
